### ISSUE TITLE
phonenumber.bundle won't work on BigSur 4Dv18R5

### ISSUE THREAD

**Issue by albanBrunet** [miyako/4d-plugin-phonenumber#3]
Hello.
I want to try this plugin but i can't open it on MacOS BigSur with a 4Dv18R5.
When i try to open the 4dbase to test, i got this message.

![Capture d’écran 2021-04-09 à 15 59 05](https://user-images.githubusercontent.com/16685672/114191270-87369e80-994c-11eb-9f45-e206705ac922.png)

Have you a solution, since i can't modify the bundle myself.

Thank you

**Comment by miyako** [comment]
the error is saying that the plugin is not notarised

**Comment by miyako** [comment]
please try https://github.com/miyako/4d-plugin-phonenumber/releases/tag/3.1.0

**Comment by albanBrunet** [comment]
It works, thank you
